const FETCHDATA='FETCH_DATA';
const FETCHSUCCESS='FETCH_SUCCESS';
const FETCHERROR='FETCH_ERROR'

const ADD_TO_CART='ADD_TO_CART';
const INCREMENT_CART='INCREMENT_CART';
const DECREMENT_CART='DECREMENT_CART';
const REMOVE_FROM_CART='REMOVE_FROM_CART';

const CLEAR_CART_SERVER_SUCCESS='CLEAR_CART_SERVER_SUCCESS';
const CLEAR_CART_SERVER_ERROR='CLEAR_CART_SERVER_ERROR';

const MOVE_TO_CART='MOVE_TO_CART';
const REMOVE_FROM_SAVE_LATER='REMOVE_FROM_SAVE_LATER';
const MOVE_TO_SAVE_LATER='MOVE_TO_SAVE_LATER';

const SERVER_SUBMIT='SERVER_SUBMIT';
const SERVER_SUBMIT_ERROR='SERVER_SUBMIT_ERROR';
const SERVER_SUBMIT_SUCCESS='SERVER_SUBMIT_SUCCESS'; 

const FETCH_SAVE_LATER_DATA='FETCH_SAVE_LATER_DATA';
const FETCH_SAVE_LATER_SUCCESS='FETCH_SAVE_LATER_SUCCESS';
const FETCH_SAVE_LATER_ERROR='FETCH_SAVE_LATER_ERROR'

const SAVE_LATER_SERVER_SUBMIT='SAVE_LATER_SERVER_SUBMIT';
const SAVE_LATER_SERVER_SUBMIT_ERROR='SAVE_LATER_SERVER_SUBMIT_ERROR';
const SAVE_LATER_SERVER_SUBMIT_SUCCESS='SAVE_LATER_SERVER_SUBMIT_SUCCESS'; 

export {
    FETCHDATA,
    FETCHSUCCESS,
    FETCHERROR,
    REMOVE_FROM_CART,
    INCREMENT_CART,
    DECREMENT_CART,
    ADD_TO_CART,
    MOVE_TO_CART,
    REMOVE_FROM_SAVE_LATER,
    MOVE_TO_SAVE_LATER,
    SERVER_SUBMIT,
    SERVER_SUBMIT_ERROR,
    SERVER_SUBMIT_SUCCESS,
    FETCH_SAVE_LATER_DATA,
    FETCH_SAVE_LATER_SUCCESS,
    FETCH_SAVE_LATER_ERROR,
    SAVE_LATER_SERVER_SUBMIT,
    SAVE_LATER_SERVER_SUBMIT_ERROR,
    SAVE_LATER_SERVER_SUBMIT_SUCCESS,
    CLEAR_CART_SERVER_SUCCESS,
    CLEAR_CART_SERVER_ERROR
} 